require "util"

-- autogenerated code-files
require ("prototypes.z_groups")
require ("prototypes.z_items")
require ("prototypes.z_fluids")
require ("prototypes.z_recipes")


-- manual code
require ("prototypes.e_farms")
require ("prototypes.e_mf-trans")
require ("prototypes.e_motor_pump")
require ("prototypes.e_assemblys")
require ("prototypes.e_sfeffe")
require ("prototypes.e_rheinsberg")
require ("prototypes.e_quantrinum-reactor")
require ("prototypes.e_andere")
require ("prototypes.recipes_mf")
require ("prototypes.r_externs")
require ("prototypes.e_pipes")
require ("prototypes.e_transport_tube")
require ("prototypes.e_wandler")




-- if problem off, fps-drops lower - with on game stalls on mouseover at any handcrafting queue, cancel can freeze game 
--require ("prototypes.y_problem_recipes")



--require ("yi_engines_016_data-updates")